[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "rustls-tls"] }
base64 = "0.21"
rand = "0.8"
aes-gcm = "0.10"
aead = "0.5"
